In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("UseCase - Airlines.xlsx")

In [3]:
df.head()

,flight_id,airline,source,destination,departure_time,arrival_time,duration
0,SJ010,SpiceJet,CCU,MAA,2026-04-20 23:38:41.701,2026-04-21 02:32:41.701,02:54:00
1,AI155,Air India,BOM,CCU,2026-04-20 23:35:41.703,2026-04-21 01:23:41.703,01:48:00
2,UK094,Vistara,BOM,CCU,2026-04-20 23:26:41.702,2026-04-21 01:11:41.702,01:45:00
3,AI245,Air India,BOM,CCU,2026-04-20 23:07:41.704,2026-04-21 01:43:41.704,02:36:00
4,AI192,Air India,MAA,BOM,2026-04-20 23:05:41.703,2026-04-21 04:04:41.703,04:59:00

In [4]:
df.shape

(1020, 7)

In [5]:
df.columns

Index(['flight_id', 'airline', 'source', 'destination', 'departure_time',
       'arrival_time', 'duration'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   flight_id       1020 non-null   object
 1   airline         979 non-null    object
 2   source          1020 non-null   object
 3   destination     1020 non-null   object
 4   departure_time  1020 non-null   datetime64[ns]
 5   arrival_time    1020 non-null   datetime64[ns]
 6   duration        1020 non-null   object
dtypes: datetime64[ns](2), object(5)
memory usage: 55.9+ KB

In [7]:
df.isnull().sum()

flight_id          0
airline           41
source             0
destination        0
departure_time     0
arrival_time       0
duration           0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(15)

In [9]:
df["airline"].value_counts(dropna=False)

airline
IndiGo       249
SpiceJet     240
Air India    236
Vistara      223
NaN           41
UNKNOWN       31
Name: count, dtype: int64

In [10]:
df["source"].value_counts(dropna=False)

source
BOM    207
HYD    180
CCU    174
DEL    163
MAA    157
BLR    139
Name: count, dtype: int64

In [11]:
df["destination"].value_counts(dropna=False)

destination
DEL    200
CCU    188
BOM    174
BLR    165
MAA    151
HYD    142
Name: count, dtype: int64

In [12]:
df["flight_id"].head(20)

0     SJ010
1     AI155
2     UK094
3     AI245
4     AI192
5     SJ158
6     6F196
7     AI080
8     6F025
9     6F251
10    AI137
11    6F026
12    UK167
13    UK027
14    AI069
15    AI058
16    AI140
17    SJ239
18    6F099
19    AI048
Name: flight_id, dtype: object

In [13]:
df["flight_id"].nunique()

1004

In [14]:
print("Departure times:")
print(df["departure_time"].head(20))

print("\nArrival times:")
print(df["arrival_time"].head(20))

print("\nDuration values:")
print(df["duration"].head(20))

Departure times:
0    2026-04-20 23:38:41.701
1    2026-04-20 23:35:41.703
2    2026-04-20 23:26:41.702
3    2026-04-20 23:07:41.704
4    2026-04-20 23:05:41.703
5    2026-04-20 23:05:41.703
6    2026-04-20 23:04:41.703
7    2026-04-20 23:03:41.702
8    2026-04-20 23:02:41.701
9    2026-04-20 22:56:41.703
10   2026-04-20 22:49:41.702
11   2026-04-20 22:46:42.000
12   2026-04-20 22:45:41.703
13   2026-04-20 22:44:41.701
14   2026-04-20 22:43:41.702
15   2026-04-20 22:40:41.701
16   2026-04-20 22:25:41.702
17   2026-04-20 22:24:41.704
18   2026-04-20 22:24:41.702
19   2026-04-20 22:23:41.701
Name: departure_time, dtype: datetime64[ns]

Arrival times:
0    2026-04-21 02:32:41.701
1    2026-04-21 01:23:41.703
2    2026-04-21 01:11:41.702
3    2026-04-21 01:43:41.704
4    2026-04-21 04:04:41.703
5    2026-04-21 01:24:41.703
6    2026-04-21 00:47:41.703
7    2026-04-21 00:35:41.702
8    2026-04-20 23:57:41.701
9    2026-04-20 23:37:41.703
10   2026-04-21 01:17:41.702
11   2026-04-21 03:13:42.000
12   2026-04-21 01:46:41.703
13   2026-04-21 01:05:41.701
14   2026-04-21 02:29:41.702
15   2026-04-21 00:18:41.701
16   2026-04-21 02:08:41.702
17   2026-04-21 00:10:41.704
18   2026-04-20 22:59:41.702
19   2026-04-21 02:15:41.701
Name: arrival_time, dtype: datetime64[ns]

Duration values:
0     02:54:00
1     01:48:00
2     01:45:00
3     02:36:00
4     04:59:00
5     02:19:00
6     01:43:00
7     01:32:00
8     00:55:00
9     00:41:00
10    02:28:00
11    04:27:00
12    03:01:00
13    02:21:00
14    03:46:00
15    01:38:00
16    03:43:00
17    01:46:00
18    00:35:00
19    03:52:00
Name: duration, dtype: object

In [15]:
df.describe(include="all")

,flight_id,airline,source,destination,departure_time,arrival_time,duration
count,1020,979,1020,1020,1020,1020,1020
unique,1004,5,6,6,NaN,NaN,270
top,6F250,IndiGo,BOM,DEL,NaN,NaN,02:49:00
freq,2,249,207,200,NaN,NaN,11
mean,NaN,NaN,NaN,NaN,2026-04-19 06:45:29.350427136,2026-04-19 09:28:24.534786048,NaN
min,NaN,NaN,NaN,NaN,2026-04-17 12:25:41.701000,2026-04-17 14:10:41.703000,NaN
25%,NaN,NaN,NaN,NaN,2026-04-18 10:43:26.701250048,2026-04-18 13:13:56.701250048,NaN
50%,NaN,NaN,NaN,NaN,2026-04-19 06:26:11.701499904,2026-04-19 09:19:11.852000,NaN
75%,NaN,NaN,NaN,NaN,2026-04-20 03:20:26.703250176,2026-04-20 06:05:41.702749952,NaN
max,NaN,NaN,NaN,NaN,2026-04-20 23:38:41.701000,2026-04-21 04:04:41.703000,NaN

In [16]:
profile = pd.DataFrame({
    "column": df.columns,
    "data_type": df.dtypes.astype(str).values,
    "missing_values": df.isnull().sum().values,
    "unique_values": df.nunique(dropna=False).values
})

profile

           column       data_type  missing_values  unique_values
0       flight_id          object               0           1004
1         airline          object              41              6
2          source          object               0              6
3     destination          object               0              6
4  departure_time  datetime64[ns]               0            981
5    arrival_time  datetime64[ns]               0            969
6        duration          object               0            270

STEP 2

In [17]:
duplicates = df[df.duplicated(keep=False)]

duplicates.sort_values(by="flight_id")

,flight_id,airline,source,destination,departure_time,arrival_time,duration
550,AI020,NaN,BOM,BLR,2026-04-19 03:53:41.701,2026-04-19 06:21:41.701,02:28:00
549,AI020,NaN,BOM,BLR,2026-04-19 03:53:41.701,2026-04-19 06:21:41.701,02:28:00
141,AI031,Air India,DEL,MAA,2026-04-20 13:05:41.701,2026-04-20 16:11:41.701,03:06:00
142,AI031,Air India,DEL,MAA,2026-04-20 13:05:41.701,2026-04-20 16:11:41.701,03:06:00
598,AI043,Air India,CCU,DEL,2026-04-19 00:28:41.701,2026-04-19 04:37:41.701,04:09:00
599,AI043,Air India,CCU,DEL,2026-04-19 00:28:41.701,2026-04-19 04:37:41.701,04:09:00
603,AI070,Air India,CCU,DEL,2026-04-19 00:05:41.702,2026-04-19 01:44:41.702,01:39:00
602,AI070,Air India,CCU,DEL,2026-04-19 00:05:41.702,2026-04-19 01:44:41.702,01:39:00
83,AI242,UNKNOWN,BLR,CCU,2026-04-20 16:41:41.704,2026-04-20 17:43:41.704,01:02:00
84,AI242,UNKNOWN,BLR,CCU,2026-04-20 16:41:41.704,2026-04-20 17:43:41.704,01:02:00
940,SJ037,SpiceJet,BLR,BOM,2026-04-17 19:14:41.701,2026-04-17 22:31:41.701,03:17:00
939,SJ037,SpiceJet,BLR,BOM,2026-04-17 19:14:41.701,2026-04-17 22:31:41.701,03:17:00
588,SJ118,SpiceJet,DEL,BOM,2026-04-19 01:08:41.702,2026-04-19 02:33:41.702,01:25:00
589,SJ118,SpiceJet,DEL,BOM,2026-04-19 01:08:41.702,2026-04-19 02:33:41.702,01:25:00
106,SJ142,SpiceJet,CCU,BOM,2026-04-20 15:14:41.702,2026-04-20 16:56:41.702,01:42:00
105,SJ142,SpiceJet,CCU,BOM,2026-04-20 15:14:41.702,2026-04-20 16:56:41.702,01:42:00
310,SJ146,SpiceJet,HYD,BLR,2026-04-19 22:37:41.702,2026-04-20 00:33:41.702,01:56:00
309,SJ146,SpiceJet,HYD,BLR,2026-04-19 22:37:41.702,2026-04-20 00:33:41.702,01:56:00
606,UK013,Vistara,BOM,MAA,2026-04-18 23:52:41.701,2026-04-19 02:52:41.701,03:00:00
605,UK013,Vistara,BOM,MAA,2026-04-18 23:52:41.701,2026-04-19 02:52:41.701,03:00:00
935,UK049,Vistara,HYD,BOM,2026-04-17 19:47:41.701,2026-04-17 20:32:41.701,00:45:00
936,UK049,Vistara,HYD,BOM,2026-04-17 19:47:41.701,2026-04-17 20:32:41.701,00:45:00
758,UK139,NaN,BLR,MAA,2026-04-18 10:54:41.703,2026-04-18 14:31:41.703,03:37:00
759,UK139,NaN,BLR,MAA,2026-04-18 10:54:41.703,2026-04-18 14:31:41.703,03:37:00
812,UK160,Vistara,BLR,BOM,2026-04-18 06:42:41.703,2026-04-18 10:58:41.703,04:16:00
813,UK160,Vistara,BLR,BOM,2026-04-18 06:42:41.703,2026-04-18 10:58:41.703,04:16:00
502,UK163,Vistara,DEL,HYD,2026-04-19 07:22:41.703,2026-04-19 09:04:41.703,01:42:00
503,UK163,Vistara,DEL,HYD,2026-04-19 07:22:41.703,2026-04-19 09:04:41.703,01:42:00
914,UK180,Vistara,CCU,MAA,2026-04-17 21:18:41.703,2026-04-17 23:29:41.703,02:11:00
915,UK180,Vistara,CCU,MAA,2026-04-17 21:18:41.703,2026-04-17 23:29:41.703,02:11:00

In [18]:
flight_id_counts = df["flight_id"].value_counts()

flight_id_counts[flight_id_counts > 1]

flight_id
6F250    2
AI031    2
UK163    2
AI242    2
SJ142    2
SJ146    2
AI020    2
SJ118    2
AI043    2
AI070    2
UK013    2
UK139    2
UK160    2
UK180    2
UK049    2
SJ037    2
Name: count, dtype: int64

In [19]:
duplicate_ids = flight_id_counts[flight_id_counts > 1].index

df[df["flight_id"].isin(duplicate_ids)].sort_values("flight_id")

,flight_id,airline,source,destination,departure_time,arrival_time,duration
253,6F250,UNKNOWN,DEL,BLR,2026-04-20 03:26:41.701,2026-04-20 07:30:41.701,04:04:00
270,6F250,UNKNOWN,CCU,BLR,2026-04-20 02:23:41.702,2026-04-20 02:56:41.702,00:33:00
550,AI020,NaN,BOM,BLR,2026-04-19 03:53:41.701,2026-04-19 06:21:41.701,02:28:00
549,AI020,NaN,BOM,BLR,2026-04-19 03:53:41.701,2026-04-19 06:21:41.701,02:28:00
141,AI031,Air India,DEL,MAA,2026-04-20 13:05:41.701,2026-04-20 16:11:41.701,03:06:00
142,AI031,Air India,DEL,MAA,2026-04-20 13:05:41.701,2026-04-20 16:11:41.701,03:06:00
599,AI043,Air India,CCU,DEL,2026-04-19 00:28:41.701,2026-04-19 04:37:41.701,04:09:00
598,AI043,Air India,CCU,DEL,2026-04-19 00:28:41.701,2026-04-19 04:37:41.701,04:09:00
603,AI070,Air India,CCU,DEL,2026-04-19 00:05:41.702,2026-04-19 01:44:41.702,01:39:00
602,AI070,Air India,CCU,DEL,2026-04-19 00:05:41.702,2026-04-19 01:44:41.702,01:39:00
83,AI242,UNKNOWN,BLR,CCU,2026-04-20 16:41:41.704,2026-04-20 17:43:41.704,01:02:00
84,AI242,UNKNOWN,BLR,CCU,2026-04-20 16:41:41.704,2026-04-20 17:43:41.704,01:02:00
939,SJ037,SpiceJet,BLR,BOM,2026-04-17 19:14:41.701,2026-04-17 22:31:41.701,03:17:00
940,SJ037,SpiceJet,BLR,BOM,2026-04-17 19:14:41.701,2026-04-17 22:31:41.701,03:17:00
588,SJ118,SpiceJet,DEL,BOM,2026-04-19 01:08:41.702,2026-04-19 02:33:41.702,01:25:00
589,SJ118,SpiceJet,DEL,BOM,2026-04-19 01:08:41.702,2026-04-19 02:33:41.702,01:25:00
106,SJ142,SpiceJet,CCU,BOM,2026-04-20 15:14:41.702,2026-04-20 16:56:41.702,01:42:00
105,SJ142,SpiceJet,CCU,BOM,2026-04-20 15:14:41.702,2026-04-20 16:56:41.702,01:42:00
310,SJ146,SpiceJet,HYD,BLR,2026-04-19 22:37:41.702,2026-04-20 00:33:41.702,01:56:00
309,SJ146,SpiceJet,HYD,BLR,2026-04-19 22:37:41.702,2026-04-20 00:33:41.702,01:56:00
605,UK013,Vistara,BOM,MAA,2026-04-18 23:52:41.701,2026-04-19 02:52:41.701,03:00:00
606,UK013,Vistara,BOM,MAA,2026-04-18 23:52:41.701,2026-04-19 02:52:41.701,03:00:00
935,UK049,Vistara,HYD,BOM,2026-04-17 19:47:41.701,2026-04-17 20:32:41.701,00:45:00
936,UK049,Vistara,HYD,BOM,2026-04-17 19:47:41.701,2026-04-17 20:32:41.701,00:45:00
759,UK139,NaN,BLR,MAA,2026-04-18 10:54:41.703,2026-04-18 14:31:41.703,03:37:00
758,UK139,NaN,BLR,MAA,2026-04-18 10:54:41.703,2026-04-18 14:31:41.703,03:37:00
812,UK160,Vistara,BLR,BOM,2026-04-18 06:42:41.703,2026-04-18 10:58:41.703,04:16:00
813,UK160,Vistara,BLR,BOM,2026-04-18 06:42:41.703,2026-04-18 10:58:41.703,04:16:00
503,UK163,Vistara,DEL,HYD,2026-04-19 07:22:41.703,2026-04-19 09:04:41.703,01:42:00
502,UK163,Vistara,DEL,HYD,2026-04-19 07:22:41.703,2026-04-19 09:04:41.703,01:42:00
914,UK180,Vistara,CCU,MAA,2026-04-17 21:18:41.703,2026-04-17 23:29:41.703,02:11:00
915,UK180,Vistara,CCU,MAA,2026-04-17 21:18:41.703,2026-04-17 23:29:41.703,02:11:00

In [20]:
df[df["airline"].isna()]

,flight_id,airline,source,destination,departure_time,arrival_time,duration
57,UK209,NaN,MAA,BLR,2026-04-20 19:02:41.704,2026-04-20 21:47:41.704,02:45:00
63,6F270,NaN,HYD,MAA,2026-04-20 18:14:41.701,2026-04-20 19:02:41.701,00:48:00
89,UK224,NaN,CCU,MAA,2026-04-20 16:25:41.704,2026-04-20 20:24:41.704,03:59:00
118,6F261,NaN,CCU,DEL,2026-04-20 14:31:41.703,2026-04-20 17:29:41.703,02:58:00
120,6F254,NaN,MAA,BLR,2026-04-20 14:26:41.703,2026-04-20 18:01:41.703,03:35:00
124,6F259,NaN,BOM,DEL,2026-04-20 14:10:41.703,2026-04-20 15:21:41.703,01:11:00
133,UK141,NaN,HYD,MAA,2026-04-20 13:38:41.703,2026-04-20 15:59:41.703,02:21:00
150,6F255,NaN,DEL,BOM,2026-04-20 11:59:41.703,2026-04-20 15:33:41.703,03:34:00
218,AI047,NaN,CCU,MAA,2026-04-20 06:36:41.701,2026-04-20 07:23:41.701,00:47:00
222,AI128,NaN,BOM,CCU,2026-04-20 06:07:41.702,2026-04-20 10:03:41.702,03:56:00
225,SJ138,NaN,BLR,BOM,2026-04-20 05:55:41.702,2026-04-20 06:43:41.702,00:48:00
279,AI009,NaN,DEL,CCU,2026-04-20 01:31:41.701,2026-04-20 04:05:41.701,02:34:00
284,AI226,NaN,BLR,HYD,2026-04-20 01:19:41.703,2026-04-20 04:08:41.703,02:49:00
299,6F272,NaN,HYD,MAA,2026-04-19 23:35:41.702,2026-04-20 00:22:41.702,00:47:00
314,SJ099,NaN,MAA,BLR,2026-04-19 22:14:41.702,2026-04-20 00:34:41.702,02:20:00
319,6F260,NaN,CCU,DEL,2026-04-19 21:51:41.702,2026-04-20 01:14:41.702,03:23:00
351,6F271,NaN,HYD,MAA,2026-04-19 19:33:41.702,2026-04-19 22:52:41.702,03:19:00
357,6F256,NaN,BOM,CCU,2026-04-19 18:40:41.702,2026-04-19 19:13:41.702,00:33:00
376,AI252,NaN,HYD,DEL,2026-04-19 17:30:41.704,2026-04-19 21:54:41.704,04:24:00
395,SJ203,NaN,DEL,HYD,2026-04-19 16:22:41.703,2026-04-19 18:27:41.703,02:05:00
398,AI168,NaN,DEL,CCU,2026-04-19 15:50:41.703,2026-04-19 20:20:41.703,04:30:00
461,AI037,NaN,BOM,BLR,2026-04-19 11:14:41.701,2026-04-19 15:13:41.701,03:59:00
482,AI219,NaN,BLR,DEL,2026-04-19 09:28:41.703,2026-04-19 11:27:41.703,01:59:00
492,SJ051,NaN,BOM,BLR,2026-04-19 08:40:41.701,2026-04-19 12:18:41.701,03:38:00
549,AI020,NaN,BOM,BLR,2026-04-19 03:53:41.701,2026-04-19 06:21:41.701,02:28:00
550,AI020,NaN,BOM,BLR,2026-04-19 03:53:41.701,2026-04-19 06:21:41.701,02:28:00
562,AI243,NaN,BLR,BOM,2026-04-19 02:50:41.704,2026-04-19 05:09:41.704,02:19:00
630,UK081,NaN,BLR,DEL,2026-04-18 22:00:41.702,2026-04-18 23:00:41.702,01:00:00
658,UK088,NaN,MAA,BLR,2026-04-18 19:16:41.702,2026-04-18 23:36:41.702,04:20:00
664,SJ225,NaN,DEL,HYD,2026-04-18 18:16:41.704,2026-04-18 20:53:41.704,02:37:00
719,6F264,NaN,DEL,HYD,2026-04-18 14:03:41.701,2026-04-18 18:23:41.701,04:20:00
758,UK139,NaN,BLR,MAA,2026-04-18 10:54:41.703,2026-04-18 14:31:41.703,03:37:00
759,UK139,NaN,BLR,MAA,2026-04-18 10:54:41.703,2026-04-18 14:31:41.703,03:37:00
774,UK151,NaN,BOM,CCU,2026-04-18 10:11:41.703,2026-04-18 13:30:41.703,03:19:00
858,6F265,NaN,DEL,HYD,2026-04-18 02:27:41.703,2026-04-18 03:24:41.703,00:57:00
870,AI125,NaN,CCU,DEL,2026-04-18 01:12:41.702,2026-04-18 04:51:41.702,03:39:00
873,UK043,NaN,DEL,HYD,2026-04-18 00:48:41.701,2026-04-18 04:52:41.701,04:04:00
880,AI065,NaN,MAA,BLR,2026-04-18 00:09:41.701,2026-04-18 05:00:41.701,04:51:00
924,AI230,NaN,CCU,BLR,2026-04-17 20:37:41.704,2026-04-18 00:22:41.704,03:45:00
925,6F268,NaN,DEL,MAA,2026-04-17 20:29:41.701,2026-04-17 21:58:41.701,01:29:00
956,AI145,NaN,DEL,BOM,2026-04-17 17:06:41.702,2026-04-17 21:31:41.702,04:25:00

In [21]:
df[df["airline"] == "UNKNOWN"]

,flight_id,airline,source,destination,departure_time,arrival_time,duration
9,6F251,UNKNOWN,DEL,BLR,2026-04-20 22:56:41.703,2026-04-20 23:37:41.703,00:41:00
14,AI069,UNKNOWN,DEL,BOM,2026-04-20 22:43:41.702,2026-04-21 02:29:41.702,03:46:00
28,UK003,UNKNOWN,HYD,DEL,2026-04-20 21:41:41.700,2026-04-21 02:19:41.700,04:38:00
58,SJ043,UNKNOWN,MAA,DEL,2026-04-20 18:59:41.701,2026-04-20 21:08:41.701,02:09:00
83,AI242,UNKNOWN,BLR,CCU,2026-04-20 16:41:41.704,2026-04-20 17:43:41.704,01:02:00
84,AI242,UNKNOWN,BLR,CCU,2026-04-20 16:41:41.704,2026-04-20 17:43:41.704,01:02:00
90,UK077,UNKNOWN,HYD,BOM,2026-04-20 16:22:41.702,2026-04-20 18:00:41.702,01:38:00
148,AI222,UNKNOWN,BOM,DEL,2026-04-20 12:10:41.703,2026-04-20 13:14:41.703,01:04:00
189,AI044,UNKNOWN,MAA,BLR,2026-04-20 09:03:41.701,2026-04-20 12:36:41.701,03:33:00
209,UK229,UNKNOWN,HYD,DEL,2026-04-20 07:40:41.704,2026-04-20 11:57:41.704,04:17:00
220,AI088,UNKNOWN,MAA,DEL,2026-04-20 06:34:41.702,2026-04-20 10:10:41.702,03:36:00
253,6F250,UNKNOWN,DEL,BLR,2026-04-20 03:26:41.701,2026-04-20 07:30:41.701,04:04:00
270,6F250,UNKNOWN,CCU,BLR,2026-04-20 02:23:41.702,2026-04-20 02:56:41.702,00:33:00
304,SJ029,UNKNOWN,HYD,DEL,2026-04-19 22:55:41.701,2026-04-20 00:22:41.701,01:27:00
394,6F253,UNKNOWN,MAA,BLR,2026-04-19 16:26:41.703,2026-04-19 18:24:41.703,01:58:00
418,AI100,UNKNOWN,CCU,BOM,2026-04-19 14:42:41.702,2026-04-19 18:22:41.702,03:40:00
443,SJ027,UNKNOWN,BOM,MAA,2026-04-19 12:50:41.701,2026-04-19 17:13:41.701,04:23:00
507,6F263,UNKNOWN,DEL,HYD,2026-04-19 07:07:41.703,2026-04-19 08:30:41.703,01:23:00
533,AI046,UNKNOWN,DEL,BOM,2026-04-19 05:09:41.701,2026-04-19 08:00:41.701,02:51:00
578,6F262,UNKNOWN,MAA,DEL,2026-04-19 01:44:41.702,2026-04-19 02:47:41.702,01:03:00
580,6F269,UNKNOWN,HYD,MAA,2026-04-19 01:30:41.702,2026-04-19 02:52:41.702,01:22:00
640,AI250,UNKNOWN,BOM,CCU,2026-04-18 20:48:41.704,2026-04-19 00:12:41.704,03:24:00
677,UK112,UNKNOWN,CCU,DEL,2026-04-18 17:05:41.702,2026-04-18 19:47:41.702,02:42:00
693,6F257,UNKNOWN,MAA,CCU,2026-04-18 16:04:41.704,2026-04-18 19:55:41.704,03:51:00
709,6F252,UNKNOWN,MAA,BLR,2026-04-18 14:25:41.701,2026-04-18 18:52:41.701,04:27:00
765,SJ140,UNKNOWN,HYD,DEL,2026-04-18 10:42:41.702,2026-04-18 14:30:41.702,03:48:00
768,SJ096,UNKNOWN,DEL,HYD,2026-04-18 10:29:41.702,2026-04-18 13:45:41.702,03:16:00
780,6F266,UNKNOWN,CCU,MAA,2026-04-18 09:49:41.703,2026-04-18 11:17:41.703,01:28:00
794,6F267,UNKNOWN,DEL,MAA,2026-04-18 07:56:41.703,2026-04-18 11:49:41.703,03:53:00
933,SJ212,UNKNOWN,MAA,BLR,2026-04-17 19:49:41.703,2026-04-17 21:44:41.703,01:55:00
996,6F258,UNKNOWN,BOM,DEL,2026-04-17 13:54:41.703,2026-04-17 16:49:41.703,02:55:00

In [22]:
sorted(df["airline"].dropna().unique())

['Air India', 'IndiGo', 'SpiceJet', 'UNKNOWN', 'Vistara']

In [23]:
routes = (
    df.groupby(["source", "destination"])
      .size()
      .reset_index(name="flight_count")
      .sort_values("flight_count", ascending=False)
)

routes

   source destination  flight_count
6     BOM         CCU            90
12    CCU         DEL            74
25    MAA         BLR            65
0     BLR         BOM            62
24    HYD         MAA            57
18    DEL         HYD            55
23    HYD         DEL            42
7     BOM         DEL            39
11    CCU         BOM            34
16    DEL         BOM            29
15    DEL         BLR            29
21    HYD         BOM            28
9     BOM         MAA            28
20    HYD         BLR            27
28    MAA         DEL            26
22    HYD         CCU            26
17    DEL         CCU            26
8     BOM         HYD            26
14    CCU         MAA            25
19    DEL         MAA            24
5     BOM         BLR            24
27    MAA         CCU            24
1     BLR         CCU            22
13    CCU         HYD            21
26    MAA         BOM            21
29    MAA         HYD            21
10    CCU         BLR            20
2     BLR         DEL            19
3     BLR         HYD            19
4     BLR         MAA            17

In [24]:
same_location = df[df["source"] == df["destination"]]

same_location

Empty DataFrame
Columns: [flight_id, airline, source, destination, departure_time, arrival_time, duration]
Index: []

In [25]:
df["calculated_duration"] = df["arrival_time"] - df["departure_time"]

df[[
    "flight_id",
    "departure_time",
    "arrival_time",
    "duration",
    "calculated_duration"
]].head(20)

,flight_id,departure_time,arrival_time,duration,calculated_duration
0,SJ010,2026-04-20 23:38:41.701,2026-04-21 02:32:41.701,02:54:00,0 days 02:54:00
1,AI155,2026-04-20 23:35:41.703,2026-04-21 01:23:41.703,01:48:00,0 days 01:48:00
2,UK094,2026-04-20 23:26:41.702,2026-04-21 01:11:41.702,01:45:00,0 days 01:45:00
3,AI245,2026-04-20 23:07:41.704,2026-04-21 01:43:41.704,02:36:00,0 days 02:36:00
4,AI192,2026-04-20 23:05:41.703,2026-04-21 04:04:41.703,04:59:00,0 days 04:59:00
5,SJ158,2026-04-20 23:05:41.703,2026-04-21 01:24:41.703,02:19:00,0 days 02:19:00
6,6F196,2026-04-20 23:04:41.703,2026-04-21 00:47:41.703,01:43:00,0 days 01:43:00
7,AI080,2026-04-20 23:03:41.702,2026-04-21 00:35:41.702,01:32:00,0 days 01:32:00
8,6F025,2026-04-20 23:02:41.701,2026-04-20 23:57:41.701,00:55:00,0 days 00:55:00
9,6F251,2026-04-20 22:56:41.703,2026-04-20 23:37:41.703,00:41:00,0 days 00:41:00
10,AI137,2026-04-20 22:49:41.702,2026-04-21 01:17:41.702,02:28:00,0 days 02:28:00
11,6F026,2026-04-20 22:46:42.000,2026-04-21 03:13:42.000,04:27:00,0 days 04:27:00
12,UK167,2026-04-20 22:45:41.703,2026-04-21 01:46:41.703,03:01:00,0 days 03:01:00
13,UK027,2026-04-20 22:44:41.701,2026-04-21 01:05:41.701,02:21:00,0 days 02:21:00
14,AI069,2026-04-20 22:43:41.702,2026-04-21 02:29:41.702,03:46:00,0 days 03:46:00
15,AI058,2026-04-20 22:40:41.701,2026-04-21 00:18:41.701,01:38:00,0 days 01:38:00
16,AI140,2026-04-20 22:25:41.702,2026-04-21 02:08:41.702,03:43:00,0 days 03:43:00
17,SJ239,2026-04-20 22:24:41.704,2026-04-21 00:10:41.704,01:46:00,0 days 01:46:00
18,6F099,2026-04-20 22:24:41.702,2026-04-20 22:59:41.702,00:35:00,0 days 00:35:00
19,AI048,2026-04-20 22:23:41.701,2026-04-21 02:15:41.701,03:52:00,0 days 03:52:00

In [26]:
overnight_flights = df[
    df["arrival_time"].dt.date > df["departure_time"].dt.date
]

overnight_flights[[
    "flight_id",
    "departure_time",
    "arrival_time",
    "duration"
]]

    flight_id          departure_time            arrival_time  duration
0       SJ010 2026-04-20 23:38:41.701 2026-04-21 02:32:41.701  02:54:00
1       AI155 2026-04-20 23:35:41.703 2026-04-21 01:23:41.703  01:48:00
2       UK094 2026-04-20 23:26:41.702 2026-04-21 01:11:41.702  01:45:00
3       AI245 2026-04-20 23:07:41.704 2026-04-21 01:43:41.704  02:36:00
4       AI192 2026-04-20 23:05:41.703 2026-04-21 04:04:41.703  04:59:00
..        ...                     ...                     ...       ...
916     6F242 2026-04-17 21:10:41.704 2026-04-18 01:04:41.704  03:54:00
918     SJ124 2026-04-17 21:05:41.702 2026-04-18 01:12:41.702  04:07:00
924     AI230 2026-04-17 20:37:41.704 2026-04-18 00:22:41.704  03:45:00
926     AI124 2026-04-17 20:28:41.702 2026-04-18 00:00:41.702  03:32:00
932     6F147 2026-04-17 19:57:41.703 2026-04-18 00:31:41.703  04:34:00

[124 rows x 4 columns]

In [27]:
len(overnight_flights)

124

In [29]:
df["duration"].apply(type).value_counts()

duration
<class 'datetime.time'>        1019
<class 'datetime.datetime'>       1
Name: count, dtype: int64

In [30]:
df[["flight_id", "duration"]].head(10)

  flight_id  duration
0     SJ010  02:54:00
1     AI155  01:48:00
2     UK094  01:45:00
3     AI245  02:36:00
4     AI192  04:59:00
5     SJ158  02:19:00
6     6F196  01:43:00
7     AI080  01:32:00
8     6F025  00:55:00
9     6F251  00:41:00

In [34]:
print(df["duration"].iloc[0])
print(type(df["duration"].iloc[0]))

02:54:00
<class 'datetime.time'>

In [35]:
import datetime

In [36]:
df[df["duration"].apply(lambda x: isinstance(x, datetime.datetime))]

,flight_id,airline,source,destination,departure_time,arrival_time,duration,calculated_duration
355,SJ192,SpiceJet,HYD,BOM,2026-04-19 18:45:42,2026-04-18 23:45:42,1899-12-29 05:00:00,-1 days +05:00:00

In [37]:
df[df["flight_id"] == "SJ192"]

,flight_id,airline,source,destination,departure_time,arrival_time,duration,calculated_duration
355,SJ192,SpiceJet,HYD,BOM,2026-04-19 18:45:42,2026-04-18 23:45:42,1899-12-29 05:00:00,-1 days +05:00:00

In [38]:
(df["arrival_time"] < df["departure_time"]).sum()

np.int64(1)

In [39]:
df.loc[df["flight_id"] == "SJ192", ["departure_time", "arrival_time", "duration", "calculated_duration"]]

,departure_time,arrival_time,duration,calculated_duration
355,2026-04-19 18:45:42,2026-04-18 23:45:42,1899-12-29 05:00:00,-1 days +05:00:00

In [41]:
df["duration_td"] = df["duration"].apply(
    lambda x: pd.Timedelta(
        hours=x.hour,
        minutes=x.minute,
        seconds=x.second
    ) if isinstance(x, datetime.time)
    else pd.Timedelta(
        days=x.day - 1,
        hours=x.hour,
        minutes=x.minute,
        seconds=x.second
    )
)

In [42]:
df["flight_id"].str.match(r"^[A-Z]{2}\d{3}$").value_counts(dropna=False)

flight_id
True     747
False    273
Name: count, dtype: int64

In [43]:
df.loc[
    ~df["flight_id"].str.match(r"^[A-Z]{2}\d{3}$"),
    "flight_id"
].value_counts().head(30)

flight_id
6F250    2
6F096    1
6F205    1
6F054    1
6F216    1
6F186    1
6F242    1
6F268    1
6F082    1
6F147    1
6F080    1
6F241    1
6F183    1
6F089    1
6F207    1
6F223    1
6F116    1
6F012    1
6F149    1
6F043    1
6F194    1
6F097    1
6F123    1
6F017    1
6F245    1
6F180    1
6F152    1
6F188    1
6F181    1
6F077    1
Name: count, dtype: int64

In [44]:
df["flight_id"].str.extract(r"^([A-Za-z0-9]+?)(\d+)$")[0].value_counts()

0
6F    273
AI    260
SJ    251
UK    236
Name: count, dtype: int64

In [47]:

print("\nMissing values:")
print(df.isna().sum())

print("\nExact duplicate rows:", df.duplicated().sum())

print("\nDuplicate flight IDs:", df["flight_id"].duplicated().sum())

print("\nAirline values:")
print(df["airline"].value_counts(dropna=False))

print("\nInvalid timestamp order:",
      (df["arrival_time"] < df["departure_time"]).sum())

Missing values:
flight_id               0
airline                41
source                  0
destination             0
departure_time          0
arrival_time            0
duration                0
calculated_duration     0
duration_td             0
dtype: int64

Exact duplicate rows: 15

Duplicate flight IDs: 16

Airline values:
airline
IndiGo       249
SpiceJet     240
Air India    236
Vistara      223
NaN           41
UNKNOWN       31
Name: count, dtype: int64

Invalid timestamp order: 1

STEP 3

In [48]:
df_clean = df.copy()

print("Original shape:", df.shape)
print("Working shape:", df_clean.shape)

Original shape: (1020, 9)
Working shape: (1020, 9)

In [49]:
df_clean = df_clean.drop_duplicates()

print("Shape after removing exact duplicates:", df_clean.shape)

Shape after removing exact duplicates: (1005, 9)

In [50]:
text_columns = ["flight_id", "airline", "source", "destination"]

for col in text_columns:
    df_clean[col] = df_clean[col].astype("string").str.strip()

print(df_clean[text_columns].head())

  flight_id    airline source destination
0     SJ010   SpiceJet    CCU         MAA
1     AI155  Air India    BOM         CCU
2     UK094    Vistara    BOM         CCU
3     AI245  Air India    BOM         CCU
4     AI192  Air India    MAA         BOM

In [51]:
df_clean["airline"] = df_clean["airline"].fillna("UNKNOWN")

print(df_clean["airline"].value_counts(dropna=False))
print("\nMissing airline values:", df_clean["airline"].isna().sum())

airline
IndiGo       249
SpiceJet     236
Air India    233
Vistara      218
UNKNOWN       69
Name: count, dtype: Int64

Missing airline values: 0

In [52]:
df_clean["duration_clean"] = df_clean["duration"].apply(
    lambda x: pd.Timedelta(
        hours=x.hour,
        minutes=x.minute,
        seconds=x.second
    ) if isinstance(x, datetime.time)
    else pd.Timedelta(
        days=x.day - 1,
        hours=x.hour,
        minutes=x.minute,
        seconds=x.second
    )
)

print(df_clean["duration_clean"].head())
print("\nDuration data type:", df_clean["duration_clean"].dtype)

0   0 days 02:54:00
1   0 days 01:48:00
2   0 days 01:45:00
3   0 days 02:36:00
4   0 days 04:59:00
Name: duration_clean, dtype: timedelta64[ns]

Duration data type: timedelta64[ns]

In [53]:
invalid_time = df_clean["arrival_time"] < df_clean["departure_time"]

df_clean.loc[invalid_time, "arrival_time"] = (
    df_clean.loc[invalid_time, "arrival_time"] + pd.Timedelta(days=1)
)

print("Invalid timestamp orders remaining:",
      (df_clean["arrival_time"] < df_clean["departure_time"]).sum())

Invalid timestamp orders remaining: 0

In [54]:
df_clean["calculated_duration"] = (
    df_clean["arrival_time"] - df_clean["departure_time"]
)

print(df_clean[[
    "flight_id",
    "departure_time",
    "arrival_time",
    "duration_clean",
    "calculated_duration"
]].head())

  flight_id          departure_time            arrival_time  duration_clean  \
0     SJ010 2026-04-20 23:38:41.701 2026-04-21 02:32:41.701 0 days 02:54:00
1     AI155 2026-04-20 23:35:41.703 2026-04-21 01:23:41.703 0 days 01:48:00
2     UK094 2026-04-20 23:26:41.702 2026-04-21 01:11:41.702 0 days 01:45:00
3     AI245 2026-04-20 23:07:41.704 2026-04-21 01:43:41.704 0 days 02:36:00
4     AI192 2026-04-20 23:05:41.703 2026-04-21 04:04:41.703 0 days 04:59:00

  calculated_duration
0     0 days 02:54:00
1     0 days 01:48:00
2     0 days 01:45:00
3     0 days 02:36:00
4     0 days 04:59:00

In [55]:
duration_match = (
    df_clean["duration_clean"] == df_clean["calculated_duration"]
)

print("Matching durations:", duration_match.sum())
print("Non-matching durations:", (~duration_match).sum())

Matching durations: 977
Non-matching durations: 28

In [56]:
print("Final shape:", df_clean.shape)

print("\nMissing values:")
print(df_clean.isna().sum())

print("\nExact duplicates:", df_clean.duplicated().sum())

print("\nInvalid timestamp orders:",
      (df_clean["arrival_time"] < df_clean["departure_time"]).sum())

Final shape: (1005, 10)

Missing values:
flight_id              0
airline                0
source                 0
destination            0
departure_time         0
arrival_time           0
duration               0
calculated_duration    0
duration_td            0
duration_clean         0
dtype: int64

Exact duplicates: 0

Invalid timestamp orders: 0

In [57]:
mismatches = df_clean[
    df_clean["duration_clean"] != df_clean["calculated_duration"]
]

print("Number of mismatches:", len(mismatches))

mismatches[[
    "flight_id",
    "airline",
    "source",
    "destination",
    "departure_time",
    "arrival_time",
    "duration_clean",
    "calculated_duration"
]].head(30)

Number of mismatches: 28

,flight_id,airline,source,destination,departure_time,arrival_time,duration_clean,calculated_duration
32,SJ149,SpiceJet,HYD,MAA,2026-04-20 21:20:41.702,2026-04-20 23:20:42,0 days 02:00:00,0 days 02:00:00.298000
93,UK109,Vistara,BLR,BOM,2026-04-20 16:06:41.702,2026-04-20 17:06:42,0 days 01:00:00,0 days 01:00:00.298000
115,AI094,Air India,DEL,BLR,2026-04-20 14:44:41.702,2026-04-20 15:44:42,0 days 01:00:00,0 days 01:00:00.298000
172,6F084,IndiGo,CCU,HYD,2026-04-20 10:34:41.702,2026-04-20 11:34:42,0 days 01:00:00,0 days 01:00:00.298000
200,UK194,Vistara,CCU,BOM,2026-04-20 08:26:41.703,2026-04-20 09:26:42,0 days 01:00:00,0 days 01:00:00.297000
265,AI068,Air India,BOM,BLR,2026-04-20 02:48:41.702,2026-04-20 04:48:42,0 days 02:00:00,0 days 02:00:00.298000
355,SJ192,SpiceJet,HYD,BOM,2026-04-19 18:45:42.000,2026-04-19 23:45:42,28 days 05:00:00,0 days 05:00:00
375,6F085,IndiGo,HYD,MAA,2026-04-19 17:32:41.702,2026-04-19 19:32:42,0 days 02:00:00,0 days 02:00:00.298000
450,6F132,IndiGo,MAA,BOM,2026-04-19 12:00:41.702,2026-04-19 13:00:42,0 days 01:00:00,0 days 01:00:00.298000
460,UK115,Vistara,BLR,BOM,2026-04-19 11:20:41.702,2026-04-19 13:20:42,0 days 02:00:00,0 days 02:00:00.298000
501,AI032,Air India,MAA,BLR,2026-04-19 07:26:41.701,2026-04-19 09:26:42,0 days 02:00:00,0 days 02:00:00.299000
510,UK118,Vistara,HYD,BLR,2026-04-19 06:22:41.702,2026-04-19 07:22:42,0 days 01:00:00,0 days 01:00:00.298000
546,AI007,Air India,MAA,DEL,2026-04-19 04:01:41.701,2026-04-19 06:01:42,0 days 02:00:00,0 days 02:00:00.299000
563,SJ246,SpiceJet,BOM,DEL,2026-04-19 02:47:41.704,2026-04-19 03:47:42,0 days 01:00:00,0 days 01:00:00.296000
565,UK157,Vistara,CCU,BOM,2026-04-19 02:41:41.703,2026-04-19 03:41:42,0 days 01:00:00,0 days 01:00:00.297000
715,6F107,IndiGo,CCU,BLR,2026-04-18 14:14:41.702,2026-04-18 17:14:42,0 days 03:00:00,0 days 03:00:00.298000
732,SJ164,SpiceJet,CCU,MAA,2026-04-18 13:14:41.703,2026-04-18 15:14:42,0 days 02:00:00,0 days 02:00:00.297000
734,UK192,Vistara,HYD,DEL,2026-04-18 12:54:41.703,2026-04-18 13:54:42,0 days 01:00:00,0 days 01:00:00.297000
764,AI008,Air India,BOM,CCU,2026-04-18 10:43:41.701,2026-04-18 12:43:42,0 days 02:00:00,0 days 02:00:00.299000
778,SJ104,SpiceJet,HYD,DEL,2026-04-18 10:00:41.702,2026-04-18 11:00:42,0 days 01:00:00,0 days 01:00:00.298000
792,SJ113,SpiceJet,BLR,BOM,2026-04-18 08:10:41.702,2026-04-18 10:10:42,0 days 02:00:00,0 days 02:00:00.298000
814,UK129,Vistara,HYD,MAA,2026-04-18 06:29:41.702,2026-04-18 07:29:42,0 days 01:00:00,0 days 01:00:00.298000
822,6F060,IndiGo,DEL,BLR,2026-04-18 05:29:41.701,2026-04-18 07:29:42,0 days 02:00:00,0 days 02:00:00.299000
850,6F006,IndiGo,BOM,BLR,2026-04-18 03:06:41.701,2026-04-18 05:06:42,0 days 02:00:00,0 days 02:00:00.299000
853,UK072,Vistara,BOM,BLR,2026-04-18 02:55:41.702,2026-04-18 05:55:42,0 days 03:00:00,0 days 03:00:00.298000
928,SJ035,SpiceJet,CCU,DEL,2026-04-17 20:15:41.701,2026-04-17 21:15:42,0 days 01:00:00,0 days 01:00:00.299000
976,6F011,IndiGo,MAA,BLR,2026-04-17 15:16:41.701,2026-04-17 17:16:42,0 days 02:00:00,0 days 02:00:00.299000
980,AI184,Air India,BOM,CCU,2026-04-17 15:03:41.703,2026-04-17 17:03:42,0 days 02:00:00,0 days 02:00:00.297000

In [58]:
df_clean["flight_duration"] = (
    df_clean["calculated_duration"].dt.total_seconds() / 60
).round().astype(int)

print(df_clean[[
    "flight_id",
    "duration_clean",
    "calculated_duration",
    "flight_duration"
]].head())

  flight_id  duration_clean calculated_duration  flight_duration
0     SJ010 0 days 02:54:00     0 days 02:54:00              174
1     AI155 0 days 01:48:00     0 days 01:48:00              108
2     UK094 0 days 01:45:00     0 days 01:45:00              105
3     AI245 0 days 02:36:00     0 days 02:36:00              156
4     AI192 0 days 04:59:00     0 days 04:59:00              299

In [59]:
print("Minimum duration:", df_clean["flight_duration"].min(), "minutes")
print("Maximum duration:", df_clean["flight_duration"].max(), "minutes")

print("Invalid durations:",
      (df_clean["flight_duration"] <= 0).sum())

Minimum duration: 30 minutes
Maximum duration: 300 minutes
Invalid durations: 0

In [60]:
print("Unique sources:", df_clean["source"].unique())
print("Unique destinations:", df_clean["destination"].unique())

same_route = (df_clean["source"] == df_clean["destination"]).sum()
print("Same source/destination flights:", same_route)

Unique sources: <StringArray>
['CCU', 'BOM', 'MAA', 'DEL', 'BLR', 'HYD']
Length: 6, dtype: string
Unique destinations: <StringArray>
['MAA', 'CCU', 'BOM', 'HYD', 'BLR', 'DEL']
Length: 6, dtype: string
Same source/destination flights: 0

In [61]:
duplicate_ids = df_clean[
    df_clean["flight_id"].duplicated(keep=False)
].sort_values("flight_id")

print("Rows belonging to duplicate flight IDs:", len(duplicate_ids))

duplicate_ids.head(30)

Rows belonging to duplicate flight IDs: 2

,flight_id,airline,source,destination,departure_time,arrival_time,duration,calculated_duration,duration_td,duration_clean,flight_duration
253,6F250,UNKNOWN,DEL,BLR,2026-04-20 03:26:41.701,2026-04-20 07:30:41.701,04:04:00,0 days 04:04:00,0 days 04:04:00,0 days 04:04:00,244
270,6F250,UNKNOWN,CCU,BLR,2026-04-20 02:23:41.702,2026-04-20 02:56:41.702,00:33:00,0 days 00:33:00,0 days 00:33:00,0 days 00:33:00,33

In [62]:
df_clean["route"] = (
    df_clean["source"] + " → " + df_clean["destination"]
)

print(df_clean[["source", "destination", "route"]].head())

  source destination      route
0    CCU         MAA  CCU → MAA
1    BOM         CCU  BOM → CCU
2    BOM         CCU  BOM → CCU
3    BOM         CCU  BOM → CCU
4    MAA         BOM  MAA → BOM

In [63]:
df_clean["airline_standardized"] = (
    df_clean["airline"]
    .str.upper()
    .str.strip()
)

print(df_clean["airline_standardized"].value_counts())

airline_standardized
INDIGO       249
SPICEJET     236
AIR INDIA    233
VISTARA      218
UNKNOWN       69
Name: count, dtype: Int64

In [64]:
df_clean["departure_date"] = df_clean["departure_time"].dt.date

print(df_clean[["departure_time", "departure_date"]].head())

           departure_time departure_date
0 2026-04-20 23:38:41.701     2026-04-20
1 2026-04-20 23:35:41.703     2026-04-20
2 2026-04-20 23:26:41.702     2026-04-20
3 2026-04-20 23:07:41.704     2026-04-20
4 2026-04-20 23:05:41.703     2026-04-20

In [65]:
df_clean["is_overnight"] = (
    df_clean["departure_time"].dt.date
    != df_clean["arrival_time"].dt.date
)

print(df_clean["is_overnight"].value_counts())

is_overnight
False    883
True     122
Name: count, dtype: int64

In [66]:
df_clean["flight_duration_hours"] = (
    df_clean["flight_duration"] / 60
).round(2)

print(
    df_clean[
        ["flight_id", "flight_duration", "flight_duration_hours"]
    ].head()
)

  flight_id  flight_duration  flight_duration_hours
0     SJ010              174                   2.90
1     AI155              108                   1.80
2     UK094              105                   1.75
3     AI245              156                   2.60
4     AI192              299                   4.98

In [68]:
print("Rows:", len(df_clean))
print("Columns:", len(df_clean.columns))

print("\nMissing values:")
print(df_clean.isna().sum().sum())

print("\nExact duplicates:", df_clean.duplicated().sum())

print(
    "\nInvalid timestamps:",
    (df_clean["arrival_time"] < df_clean["departure_time"]).sum()
)

print(
    "Invalid durations:",
    (df_clean["flight_duration"] <= 0).sum()
)

print(
    "Overnight flights:",
    df_clean["is_overnight"].sum()
)

print("\nFinal columns:")
print(df_clean.columns.tolist())

Rows: 1005
Columns: 16

Missing values:
0

Exact duplicates: 0

Invalid timestamps: 0
Invalid durations: 0
Overnight flights: 122

Final columns:
['flight_id', 'airline', 'source', 'destination', 'departure_time', 'arrival_time', 'duration', 'calculated_duration', 'duration_td', 'duration_clean', 'flight_duration', 'route', 'airline_standardized', 'departure_date', 'is_overnight', 'flight_duration_hours']

In [69]:
avg_duration = df_clean["flight_duration_hours"].mean()

print(f"Average Flight Duration: {avg_duration:.2f} hours")

Average Flight Duration: 2.74 hours

In [70]:
route_traffic = (
    df_clean.groupby("route")
    .size()
    .reset_index(name="flight_count")
    .sort_values("flight_count", ascending=False)
)

route_traffic

        route  flight_count
6   BOM → CCU            90
12  CCU → DEL            72
25  MAA → BLR            65
0   BLR → BOM            60
24  HYD → MAA            57
18  DEL → HYD            54
23  HYD → DEL            42
7   BOM → DEL            39
11  CCU → BOM            33
15  DEL → BLR            29
16  DEL → BOM            28
21  HYD → BOM            27
9   BOM → MAA            27
8   BOM → HYD            26
28  MAA → DEL            26
22  HYD → CCU            26
17  DEL → CCU            26
20  HYD → BLR            26
27  MAA → CCU            24
14  CCU → MAA            24
5   BOM → BLR            23
19  DEL → MAA            23
1   BLR → CCU            21
13  CCU → HYD            21
26  MAA → BOM            21
29  MAA → HYD            21
10  CCU → BLR            20
2   BLR → DEL            19
3   BLR → HYD            19
4   BLR → MAA            16

In [71]:
airline_distribution = (
    df_clean.groupby("airline_standardized")
    .size()
    .reset_index(name="flight_count")
    .sort_values("flight_count", ascending=False)
)

airline_distribution

  airline_standardized  flight_count
1               INDIGO           249
2             SPICEJET           236
0            AIR INDIA           233
4              VISTARA           218
3              UNKNOWN            69

In [72]:
airline_duration = (
    df_clean.groupby("airline_standardized")["flight_duration_hours"]
    .mean()
    .reset_index(name="average_duration_hours")
    .sort_values("average_duration_hours", ascending=False)
)

airline_duration

  airline_standardized  average_duration_hours
1               INDIGO                2.795261
3              UNKNOWN                2.767826
2             SPICEJET                2.736525
0            AIR INDIA                2.718841
4              VISTARA                2.711376

In [73]:
anomaly_summary = {
    "Missing/Unknown Airlines": (df_clean["airline_standardized"] == "UNKNOWN").sum(),
    "Overnight Flights": df_clean["is_overnight"].sum(),
    "Duplicate Flight IDs": df_clean["flight_id"].duplicated().sum()
}

anomaly_summary

{'Missing/Unknown Airlines': np.int64(69),
 'Overnight Flights': np.int64(122),
 'Duplicate Flight IDs': np.int64(1)}

In [74]:
duplicate_flight_ids = df_clean[
    df_clean["flight_id"].duplicated(keep=False)
].sort_values("flight_id")

duplicate_flight_ids

,flight_id,airline,source,destination,departure_time,arrival_time,duration,calculated_duration,duration_td,duration_clean,flight_duration,route,airline_standardized,departure_date,is_overnight,flight_duration_hours
253,6F250,UNKNOWN,DEL,BLR,2026-04-20 03:26:41.701,2026-04-20 07:30:41.701,04:04:00,0 days 04:04:00,0 days 04:04:00,0 days 04:04:00,244,DEL → BLR,UNKNOWN,2026-04-20,False,4.07
270,6F250,UNKNOWN,CCU,BLR,2026-04-20 02:23:41.702,2026-04-20 02:56:41.702,00:33:00,0 days 00:33:00,0 days 00:33:00,0 days 00:33:00,33,CCU → BLR,UNKNOWN,2026-04-20,False,0.55

In [75]:
df_clean.to_csv("cleaned_airlines.csv", index=False)

print("Cleaned dataset saved successfully.")
print("Final rows:", len(df_clean))

Cleaned dataset saved successfully.
Final rows: 1005